In [16]:
import polars as pl
import pandas as pd

In [24]:
df = pd.read_csv('trading_data_2024-05-22.csv')
df.head()

,Unnamed: 0,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,换手率,市盈率,量比,...,市净率,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,2,18.99,21.11,3.31,91840,164075767.86,24.36,14.11,15.84,8.13,...,3.46,-12.45,-24.4,21939215.0,15.72,-,-,-,-,2
1,2,17.26,20.03,2.88,517902,864001589.0,15.72,24.05,-11.08,3.34,...,-64.58,-14.26,-42.22,242038535.0,-9.26,-,-,-,-,2
2,2,135.7,20.0,22.62,79763,987882000.48,23.6,57.89,75.73,0.93,...,9.91,423.53,423.53,31656301.0,76.27,-,-,-,-,2
3,2,70.07,20.0,11.68,63355,423091951.31,11.83,13.11,36.65,5.07,...,2.84,10.94,-9.63,88519302.0,25.37,-,-,-,-,2
4,2,12.18,20.0,2.03,453005,529785225.0,16.26,49.46,82.48,3.59,...,2.22,50.56,8.46,78158933.0,57.32,-,-,-,-,2